const el=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100),date=s=>new Date(s).toLocaleString('es-PR',{timeZone:'America/Puerto_Rico'});let offset=0,current=null;
function message(text,error=false){el('message').textContent=text;el('message').className=error?'error':''}
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function button(text,action,cls){const b=node('button',text,cls);b.type='button';b.onclick=action;return b}
async function api(params){const res=await fetch(RECORD_API+'?'+new URLSearchParams(params),{headers:{Authorization:'Bearer '+sessionStorage.getItem('lewar-session')},cache:'no-store'});const data=await res.json();if(res.status===401){sessionStorage.removeItem('lewar-session');showAuth();throw Error('La sesión venció. Inicia sesión otra vez.')}if(!res.ok)throw Error(data.error||'No se pudo cargar');return data}
function showAuth(){const logged=!!sessionStorage.getItem('lewar-session');el('login').hidden=logged;el('registry').hidden=!logged}
el('signin').onclick=()=>{const state=crypto.randomUUID();sessionStorage.setItem('lewar-login-state',state);location.href='https://lewar-convencion-whirlpool.emmatowwerz15.chatgpt.site/conectar?state='+encodeURIComponent(state)};
el('signout').onclick=()=>{sessionStorage.removeItem('lewar-session');sessionStorage.removeItem('lewar-edit-order');showAuth();message('Sesión cerrada.')};el('new-order').onclick=()=>sessionStorage.removeItem('lewar-edit-order');
async function list(){message('Cargando órdenes…');try{const data=await api({q:el('search').value,offset:String(offset)});el('rows').replaceChildren();for(const order of data.orders){const tr=document.createElement('tr');const id=node('td');id.append(node('strong',order.id),node('p',date(order.createdAt),'muted'));const customer=node('td');customer.append(node('strong',order.cliente),node('p',order.vendedor,'muted'));tr.append(id,customer,node('td',money(order.total)),node('td',order.status,order.status),node('td',order.emailState==='service_accepted'?'Procesado por el servicio':'Sin confirmación'));const action=node('td');action.append(button('Ver orden',()=>detail(order.id)));tr.append(action);el('rows').append(tr)}if(!data.orders.length){const tr=node('tr'),td=node('td','No hay órdenes para esta búsqueda.');td.colSpan=6;tr.append(td);el('rows').append(tr)}el('prev').disabled=offset===0;el('next').disabled=!data.more;el('page-number').textContent='Página '+(offset/100+1);message('Sesión: '+data.email)}catch(e){message(e.message,true)}}
async function download(order){try{const bytes=await orderPdf(order),url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=node('a');a.href=url;a.download=order.id+'-v'+order.version+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}catch(e){message(e.message,true)}}
async function detail(id){message('Cargando detalle…');try{const data=await api({id});current=data.order;const o=current,panel=el('detail');panel.hidden=false;panel.replaceChildren(node('h2',o.id),node('p','Versión '+o.version+' · '+o.status,o.status));const grid=node('div',undefined,'details');for(const [label,value] of [['Cliente',o.cliente],['Vendedor',o.vendedor],['Contacto',o.contacto],['Teléfono',o.telefono],['Correo',o.correo],['Creada',date(o.createdAt)],['Último cambio',date(o.updatedAt)],['Subtotal',money(o.total)]]){const p=node('p');p.append(node('strong',label+': '),document.createTextNode(value));grid.append(p)}panel.append(grid);const table=node('table'),thead=node('thead'),head=node('tr');for(const t of ['Modelo','Cantidad','Precio/u','Importe'])head.append(node('th',t));thead.append(head);table.append(thead);const tbody=node('tbody');for(const line of o.lines){const tr=node('tr');tr.append(node('td',line.product.modelo+(line.manual?' · Manual':'')),node('td',String(line.quantity)),node('td',money(Math.round(line.unit*100))),node('td',money(line.total)));tbody.append(tr)}table.append(tbody);const scroll=node('div',undefined,'scroll');scroll.append(table);panel.append(scroll,node('p','Notas: '+(o.nota||'Ninguna')));if(o.changeReason)panel.append(node('p','Motivo: '+o.changeReason));const actions=node('div',undefined,'bar');actions.append(button('Descargar PDF',()=>download(o)));if(o.status!=='cancelada'){actions.append(button('Modificar orden',()=>{sessionStorage.setItem('lewar-edit-order',JSON.stringify(o));location.href='./'},'primary'));actions.append(button('Cancelar orden',()=>cancelUI(o),'danger'))}panel.append(actions,node('h2','Historial de cambios'));for(const event of data.events){const d=node('details'),summary=node('summary',`Versión ${event.version} · ${event.action} · ${date(event.created_at)}`);d.append(summary,node('p',event.actor),node('p',event.data.changeReason||'Registro inicial'));const lines=event.data.lines.map(l=>`${l.quantity} × ${l.product.modelo} · ${money(l.total)}`).join('\n');d.append(node('pre',lines+'\nSubtotal: '+money(event.data.total)),button('PDF de esta versión',()=>download({...event.data,id:o.id,version:event.version,status:event.action==='cancelada'?'cancelada':'activa'})));panel.append(d)}panel.scrollIntoView({behavior:'smooth',block:'start'});message('Detalle actualizado.')}catch(e){message(e.message,true)}}
function cancelUI(o){if(el('cancel-box'))return;const box=node('div');box.id='cancel-box';box.style.marginTop='24px';const label=node('label','Motivo de cancelación');label.htmlFor='cancel-reason';const reason=node('textarea');reason.id='cancel-reason';reason.maxLength=1000;box.append(node('h3','Cancelar '+o.id),node('p','La orden se conservará como cancelada. Se enviará el aviso a invoice@lewardistributors.com.'),label,reason);const confirm=button('Confirmar cancelación y notificar a Crédito',async()=>{if(!reason.value.trim()){reason.focus();return}confirm.disabled=true;try{const result=await recordRequest('cancel',{id:o.id,version:o.version,reason:reason.value});message('Orden cancelada y guardada. Preparando aviso…');await list();await detail(o.id);const bytes=await orderPdf(result.order);submitOrderEmail(result.order,bytes,result.receipt)}catch(e){message('Verifica el estado de la orden. '+e.message,true);confirm.disabled=false}},'danger');box.append(confirm,button('Volver',()=>box.remove()));el('detail').append(box);reason.focus()}
el('refresh').onclick=()=>{offset=0;list()};el('search').onkeydown=e=>{if(e.key==='Enter'){offset=0;list()}};el('prev').onclick=()=>{offset=Math.max(0,offset-100);list()};el('next').onclick=()=>{offset+=100;list()};
const params=new URLSearchParams(location.hash.slice(1));if(params.has('token')){const state=sessionStorage.getItem('lewar-login-state');if(state&&params.get('state')===state){sessionStorage.setItem('lewar-session',params.get('token'));sessionStorage.removeItem('lewar-login-state')}else message('No se pudo verificar el inicio de sesión. Intenta otra vez.',true);history.replaceState(null,'',location.pathname)}showAuth();if(sessionStorage.getItem('lewar-session'))list();
