const EMAIL_SERVICE_ENABLED=true;
const $=id=>document.getElementById(id),usd=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
let products=[],order,invalid=false,sending=false,submitted=false,pendingOrder=null;
function calculate(){const quantities={},overrides={};invalid=false;for(const p of products){const el=$('qty-'+p.modelo),manual=$('manual-'+p.modelo);if(manual.value!==''||manual.validity.badInput){if(!manual.checkValidity())invalid=true;else overrides[p.modelo]=Number(manual.value)}el.disabled=!Number.isFinite(p.precio)&&!Number.isFinite(overrides[p.modelo]);if(!el.disabled&&!el.checkValidity())invalid=true;quantities[p.modelo]=Number(el.value)}order=priceOrder(products,quantities,overrides);$('detalle').replaceChildren();for(const line of order.lines){const {product:p,quantity:q,unit,volume,manual,total}=line;$('price-'+p.modelo).textContent=unit===null?'Precio pendiente':usd(unit)+' c/u'+(manual?' · Manual':volume?' · Volumen':'')+(q?'\n'+usd(total/100):'');if(q){const row=document.createElement('p');row.textContent=`${q} × ${p.modelo} · ${usd(total/100)}`;$('detalle').append(row)}}$('modelos').textContent=order.lines.filter(l=>l.quantity).length;$('unidades').textContent=order.units;$('subtotal').textContent=usd(order.total/100);$('enviar').disabled=sending||submitted||invalid||!order.units;if(!sending&&!submitted)$('estado').textContent=invalid?'Revisa las cantidades (0 a 999) y los precios manuales (máximo 2 decimales, sin negativos).':order.units?'Al procesar, se enviarán los datos y el PDF a invoice@lewardistributors.com.':'Agrega artículos para preparar el pedido.'}
async function load(){try{const response=await fetch('./catalogo.json',{cache:'no-store'});if(!response.ok)throw Error();const data=await response.json();products=data.productos;$('catalogo').className='';$('catalogo').replaceChildren();for(const p of products){const row=document.createElement('div');row.className='item';row.dataset.search=[p.modelo,p.marca,p.descripcion,p.categoria].join(' ').toLowerCase();const info=document.createElement('div'),strong=document.createElement('strong'),desc=document.createElement('small'),rule=document.createElement('p');strong.textContent=p.modelo;desc.textContent=p.marca+' · '+p.descripcion;rule.className='hint';rule.textContent=(Number.isFinite(p.precio_volumen)?`${usd(p.precio)} regular · ${usd(p.precio_volumen)} desde 3 ${p.regla==='mismo_modelo'?'del mismo modelo':'combinadas'}`:'Sin precio de volumen')+(p.nota?' · '+p.nota:'');info.append(strong,desc,rule);const input=document.createElement('input');input.type='number';input.min='0';input.max='999';input.step='1';input.value='0';input.id='qty-'+p.modelo;input.disabled=!Number.isFinite(p.precio);input.setAttribute('aria-label','Cantidad de '+p.modelo);input.addEventListener('input',calculate);const price=document.createElement('div');price.className='money';price.style.whiteSpace='pre-line';price.id='price-'+p.modelo;const manualBox=document.createElement('div');manualBox.style.gridColumn='1 / -1';manualBox.style.maxWidth='260px';const label=document.createElement('label');label.htmlFor='manual-'+p.modelo;label.textContent='Precio unitario manual ($)';label.style.fontSize='14px';const manualInput=document.createElement('input');manualInput.type='number';manualInput.min='0';manualInput.max='999999.99';manualInput.step='0.01';manualInput.placeholder='Vacío = automático';manualInput.id='manual-'+p.modelo;manualInput.setAttribute('aria-label','Precio unitario manual de '+p.modelo);manualInput.addEventListener('input',calculate);manualBox.append(label,manualInput);row.append(info,input,price,manualBox);$('catalogo').append(row)}$('vigencia').textContent=data.vigencia;calculate()}catch(e){$('catalogo').textContent='No se pudo cargar el catálogo. Recarga la página.';$('enviar').disabled=true}}
$('buscar').addEventListener('input',()=>{const query=$('buscar').value.toLowerCase().trim();for(const row of $('catalogo').children)row.style.display=row.dataset.search.includes(query)?'':'none'});
function field(id){return $(id).value.trim()}
$('enviar').addEventListener('click',async()=>{
 if(sending||submitted)return;calculate();if(invalid||!order.units)return;
 for(const id of ['cliente','contacto','telefono','correo','vendedor']){if(!field(id)||!$(id).reportValidity()){$(id).focus();return}}
 const data={cliente:field('cliente'),tipo:field('tipo'),contacto:field('contacto'),telefono:field('telefono'),correo:field('correo'),vendedor:field('vendedor'),nota:field('nota'),lines:order.lines.filter(l=>l.quantity),total:order.total};
 const fingerprint=JSON.stringify(data);
 if(!pendingOrder||pendingOrder.fingerprint!==fingerprint){const now=new Date();pendingOrder={fingerprint,id:'EXPO26-'+crypto.randomUUID().replaceAll('-','').slice(0,16).toUpperCase(),date:now.toLocaleString('es-PR',{timeZone:'America/Puerto_Rico'})}}
 Object.assign(data,{id:pendingOrder.id,date:pendingOrder.date});sending=true;$('enviar').disabled=true;$('estado').textContent='Generando PDF y enviando pedido '+data.id+'…';
 const controls=[...document.querySelectorAll('input,select,textarea')].filter(el=>!el.disabled);controls.forEach(el=>el.disabled=true);
 let requestStarted=false;
 try{
  const logoResponse=await fetch('./lewar-logo.png');if(!logoResponse.ok)throw Error('No se pudo cargar el encabezado del PDF.');
  const bytes=await createOrderPdf(data,await logoResponse.arrayBuffer());const pdf=new Blob([bytes],{type:'application/pdf'});
  const download=$('descargar-pedido');if(download.href.startsWith('blob:'))URL.revokeObjectURL(download.href);download.href=URL.createObjectURL(pdf);download.download=data.id+'.pdf';download.style.display='block';
  const form=new FormData();form.append('_subject','PEDIDO '+data.id+' | '+data.cliente);form.append('_template','table');form.append('_captcha','false');form.append('_replyto',data.correo);
  const fields={'Número de orden':data.id,'Fecha y hora (Puerto Rico)':data.date,'Cliente':data.cliente,'Tipo':data.tipo,'Contacto':data.contacto,'Teléfono':data.telefono,'Correo del cliente':data.correo,'Vendedor':data.vendedor,'Artículos':data.lines.map(l=>`${l.quantity} x ${l.product.modelo} | ${usd(l.unit)} c/u | ${usd(l.total/100)}${l.manual?' | PRECIO MANUAL (automático: '+(l.automaticUnit===null?'pendiente':usd(l.automaticUnit))+')':l.volume?' | Volumen':''}`).join('\n'),'Subtotal':usd(data.total/100),'Notas':data.nota||'Ninguna','Condiciones':'Sujeto a disponibilidad y confirmación. Impuestos, entrega y términos por confirmar.'};
  for(const [key,value]of Object.entries(fields))form.append(key,value);form.append('attachment',pdf,data.id+'.pdf');
  if(!EMAIL_SERVICE_ENABLED){$('estado').textContent='PDF '+data.id+' generado. El envío automático aún no está habilitado. Descarga el PDF para revisarlo.';controls.forEach(el=>el.disabled=false);return;}
  const nativeForm=document.createElement('form');nativeForm.method='POST';nativeForm.action='https://formsubmit.co/invoice@lewardistributors.com';nativeForm.enctype='multipart/form-data';nativeForm.style.display='none';
  for(const [name,value] of form.entries()){if(name==='attachment')continue;const input=document.createElement('input');input.type='hidden';input.name=name;input.value=value;nativeForm.append(input)}
  const next=document.createElement('input');next.type='hidden';next.name='_next';next.value=new URL('./pedido-recibido.html',location.href).href;nativeForm.append(next);
  const fileInput=document.createElement('input');fileInput.type='file';fileInput.name='attachment';fileInput.accept='application/pdf';const transfer=new DataTransfer();transfer.items.add(new File([pdf],data.id+'.pdf',{type:'application/pdf'}));fileInput.files=transfer.files;nativeForm.append(fileInput);
  if(fileInput.files.length!==1||!fileInput.files[0].size)throw Error('No se pudo adjuntar el PDF. Descárgalo y vuelve a intentar.');
  try{sessionStorage.setItem('ultimo-pedido',JSON.stringify({id:data.id,total:usd(data.total/100)}));let binary='';for(const b of bytes)binary+=String.fromCharCode(b);sessionStorage.setItem('ultimo-pedido-pdf',btoa(binary))}catch(e){sessionStorage.removeItem('ultimo-pedido-pdf')}
  document.body.append(nativeForm);requestStarted=true;submitted=true;$('enviar').textContent='Enviando pedido…';$('estado').textContent='Enviando el pedido y el PDF adjunto. Espera la confirmación.';nativeForm.submit();

 }catch(error){$('estado').textContent=error.activation?error.message:requestStarted?'No se pudo confirmar el envío de '+data.id+'. Verifica en invoice antes de reintentar para evitar duplicados. Puedes descargar el PDF.':'No se pudo preparar el pedido: '+error.message;controls.forEach(el=>el.disabled=false)}
 finally{sending=false;$('enviar').disabled=submitted;}
});load();
