async function createOrderPdf(data,logoBytes){
 const {PDFDocument,StandardFonts,rgb}=PDFLib,doc=await PDFDocument.create();
 const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),logo=await doc.embedPng(logoBytes);
 const ink=rgb(.12,.16,.20),gold=rgb(.68,.52,.25),gray=rgb(.39,.43,.47),light=rgb(.95,.96,.97);
 const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
 const clean=t=>String(t??'').replace(/[^\x20-\x7E\xA0-\xFF\n]/g,' ');
 let page,y;
 function text(t,x,yy,size=10,font=regular,color=ink){page.drawText(clean(t),{x,y:yy,size,font,color})}
 function wrap(t,width,size=10,font=regular){let result=[],line='';for(const token of clean(t).split(/\s+/)){let parts=[token];if(font.widthOfTextAtSize(token,size)>width){parts=[];let part='';for(const c of token){if(font.widthOfTextAtSize(part+c,size)>width){parts.push(part);part=''}part+=c}if(part)parts.push(part)}for(const word of parts){const next=line?line+' '+word:word;if(font.widthOfTextAtSize(next,size)>width){if(line)result.push(line);line=word}else line=next}}if(line)result.push(line);return result.length?result:['-']}
 function newPage(){page=doc.addPage([612,792]);page.drawImage(logo,{x:36,y:696,width:68,height:68});text('LEWAR LOGDISTRIBUTORS',119,744,16,bold);text('Expo Muebles 2026 · Solicitud de pedido',119,724,10,regular,gray);text(data.id+' · v'+(data.version||1)+(data.status==='cancelada'?' · CANCELADA':''),119,704,10,bold,gold);page.drawLine({start:{x:36,y:683},end:{x:576,y:683},thickness:1,color:gold});y=659}
 function ensure(height){if(y-height<66)newPage()}
 function block(label,value){const lines=wrap(value,425);ensure(lines.length*14+9);text(label,36,y,10,bold);for(const line of lines){text(line,150,y);y-=14}y-=5}
 function tableHead(){ensure(40);page.drawRectangle({x:36,y:y-8,width:540,height:25,color:ink});text('MODELO / DESCRIPCIÓN',44,y,9,bold,rgb(1,1,1));text('CANT.',330,y,9,bold,rgb(1,1,1));text('PRECIO/U',389,y,9,bold,rgb(1,1,1));text('IMPORTE',494,y,9,bold,rgb(1,1,1));y-=29}
 newPage();block('Fecha / hora',data.date+' (Puerto Rico)');block('Cliente',data.cliente);block('Tipo de cliente',data.tipo);block('Contacto',data.contacto);block('Teléfono',data.telefono);block('Correo',data.correo);block('Vendedor',data.vendedor);y-=8;tableHead();
 for(const [i,l] of data.lines.entries()){const desc=wrap(l.product.marca+' · '+l.product.descripcion,266,9);const height=27+desc.length*12+((l.volume||l.manual)?12:0);if(y-height<70){newPage();tableHead()}if(i%2===0)page.drawRectangle({x:36,y:y-height+8,width:540,height,color:light});text(l.product.modelo,44,y,10,bold);text(String(l.quantity),337,y);text(money(l.unit),389,y);text(money(l.total/100),494,y);let dy=y-15;for(const line of desc){text(line,44,dy,9,regular,gray);dy-=12}if(l.manual)text('Precio manual · Automático: '+(l.automaticUnit===null?'pendiente':money(l.automaticUnit)),44,dy,8,regular,gold);else if(l.volume)text('Precio de volumen aplicado',44,dy,8,regular,gold);y-=height}
 ensure(100);y-=13;text('SUBTOTAL',365,y,12,bold);text(money(data.total/100),480,y,14,bold);y-=30;if(data.changeReason)block('Motivo del cambio',data.changeReason);block('Notas',data.nota||'Ninguna');const note=data.status==='cancelada'?'ORDEN CANCELADA. No procesar. Se conserva este documento como registro de la cancelación.':'Sujeto a disponibilidad y confirmación de Lewar. Impuestos, entrega y términos comerciales por confirmar.';for(const line of wrap(note,540,9)){ensure(15);text(line,36,y,9,regular,gray);y-=13}
 const pages=doc.getPages();pages.forEach((p,i)=>{p.drawText(clean(data.id),{x:36,y:32,size:8,font:regular,color:gray});p.drawText(`Página ${i+1} de ${pages.length}`,{x:491,y:32,size:8,font:regular,color:gray})});doc.setTitle('Pedido '+data.id);doc.setAuthor('Lewar LogDistributors');doc.setCreator('Lewar LogDistributors');doc.setProducer('Lewar LogDistributors');return doc.save();
}
if(typeof module!=='undefined')module.exports={createOrderPdf};
