create table if not exists public.expo_orders (
  id text primary key,
  request_key uuid unique,
  version integer not null default 1,
  status text not null default 'activa',
  receipt text,
  email_state text not null default 'pending',
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expo_order_events (
  event_id bigint generated by default as identity primary key,
  order_id text not null references public.expo_orders(id) on delete cascade,
  version integer not null,
  action text not null,
  actor text not null default 'Expo Muebles',
  reason text,
  data jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists expo_orders_created_at_idx on public.expo_orders(created_at desc);
create index if not exists expo_orders_search_idx on public.expo_orders using gin (data);
create index if not exists expo_order_events_order_idx on public.expo_order_events(order_id, version desc);

alter table public.expo_orders enable row level security;
alter table public.expo_order_events enable row level security;
